services:
  - type: web
    name: meu-site-django
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn nome_do_projeto.wsgi
    envVars:
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: meu-site-django.onrender.com
