services:
  - type: web
    name: projetomaquinas
    env: python
    buildCommand: pip install -r requirements.txt && python manage.py migrate && python manage.py collectstatic --noinput
    startCommand: gunicorn nome_do_projeto.wsgi:application
    staticPublishPath: staticfiles
    envVars:
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: projetomaquinas.onrender.com