# Generated by Django 5.2.1 on 2025-06-06 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='peca',
            name='maquina',
            field=models.CharField(default='indefinido', max_length=100),
            preserve_default=False,
        ),
    ]
