# Generated by Django 5.2.1 on 2025-06-09 13:40

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_peca_maquina'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='peca',
            name='adicionada_em',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 6, 9, 13, 40, 21, 808356, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='peca',
            name='adicionada_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='peca',
            name='codigo',
            field=models.CharField(max_length=50),
        ),
    ]
